### ISSUE TITLE
Error when resplitting the data

### ISSUE THREAD

**Issue by ryskina** [davidgu13/Lemma-vs-Form-Splits#1]
I cloned https://github.com/sigmorphon2020/task0-data/, copied `generate_lemma_splits.py` into the same folder and tried running it, but got the following error:

```
Generating new datasets:
Traceback (most recent call last):
  File "generate_lemma_splits.py", line 160, in <module>
    datasets = generate_new_datasets(*paths[:-1]) # returns 4 datasets - train, dev, test X 2
  File "generate_lemma_splits.py", line 73, in generate_new_datasets
    assert sum([train_prop, dev_prop, test_prop])==1
AssertionError
```

What might be the issue here?

**Comment by ryskina** [comment]
Looks like it might be a platform-dependent precision issue. I replaced the assertion statement with `assert np.isclose(sum([train_prop, dev_prop, test_prop]), 1, atol=1e-08)`and it works for me now.

**Comment by davidgu13** [comment]
Hi @ryskina,
Thank you for your comment! I'll update that line soon.
David
